core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tournament.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    
# urlpatterns += staticfiles_urlpatterns()

tournament/urls.py
from django.urls import path
from .views import *

app_name = 'tournament'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('upload_replay/', ReplayFormView.as_view(), name='upload_replay'),
    path('replay_list/', ReplayListView.as_view(), name='replay_list'),
    path('download_replay/<path:file_path>/', ReplayDownload.as_view(), name='download_replay'),
    path('tournament_list', TournamentListView.as_view(), name='tournament_list'),
    path('tournament/<int:pk>', TournamentDetailView.as_view(), name='tournament_detail'),
    path('tournament/<int:pk>/enter_tournament/', enter_tournament, name='enter_tournament'),
    path('tournament/<int:pk>/leave_tournament/', leave_tournament, name='leave_tournament'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% comment %} Тест фронтенда загрузки реплея {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'css/update_replay_form.css' %}">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> {% endcomment %}
    
    <title>
        {% block title %}wot tournament{% endblock %}
    </title>
</head>
<body>
    {% block menu %}
        <ul>
            <li><a href="{% url 'tournament:index' %}">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'profile' %}">Мой профиль {{ user.username }}</a></li>
                <li><a href="{% url 'logout' %}?next={{request.path}}">Выйти</a></li>
                <li><a href="{% url 'users' %}">Пользователи</a></li>
            {% else %}
                <li><a href="{% url 'login' %}?next={{request.path}}">Войти</a></li>
                <li><a href="{% url 'register' %}">Регистрация</a></li>
            {% endif %}
            <li><a href="{% url 'tournament:tournament_list' %}">Турниры</a></li>
            <hr>
        </ul>
    {% endblock %}

    {% block content %}
    {% endblock %}
    {% comment %} Тест фронтенда загрузки реплея {% endcomment %}
    {% comment %} <script src="{% static 'js/update_replay_form.js' %}"></script> {% endcomment %}
</body>
</html>