core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tournament.urls')),
    path('accounts/', include('accounts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    
# urlpatterns += staticfiles_urlpatterns()

tournament/urls.py
from django.urls import path
from .views import *

app_name = 'tournament'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('upload_replay/', ReplayFormView.as_view(), name='upload_replay'),
    path('replay_list/', ReplayListView.as_view(), name='replay_list'),
    path('download_replay/<path:file_path>/', ReplayDownload.as_view(), name='download_replay'),
    path('tournament_list', TournamentListView.as_view(), name='tournament_list'),
    path('tournament/<int:pk>', TournamentDetailView.as_view(), name='tournament_detail'),
    path('tournament/<int:pk>/enter_tournament/', enter_tournament, name='enter_tournament'),
    path('tournament/<int:pk>/leave_tournament/', leave_tournament, name='leave_tournament'),
]

tournament/models.py
from email.policy import default
from tabnanny import verbose
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, FileExtensionValidator, validate_image_file_extension
from .validators import *
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()

class Tank(models.Model):
    class TankLevelChoice(models.TextChoices):
        TT = 'ТТ'
        ST = 'СТ'
        PT = 'ПТ'
        LT = 'ЛТ'
        CAU = 'САУ'
        
    name = models.CharField(
        max_length=100,
        unique=True,
        verbose_name='название',
    )
    
    level = models.IntegerField(
        validators=[tank_level_validators],
        verbose_name='уровен',
    )
    
    tank_type = models.CharField(
        verbose_name='тип',
        choices=TankLevelChoice.choices,
        max_length=5
    )
    
    is_premium = models.BooleanField(
        verbose_name='премиумный',
        default=False,
    )
    
    image = models.ImageField(
        verbose_name='фото',
        upload_to='tanks/',
        default='tanks/default_tank_icon.png',
        help_text = 'размер фотографии должен быть 1x1\n в формате png',
        validators = [
            FileExtensionValidator(allowed_extensions=['png']),
            # ImageSizeValidator(),
        ],
    )
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['level', 'tank_type', 'name']
        verbose_name = 'Танк'
        verbose_name_plural = 'Танки'
        
    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args, **kwargs)

     

class Tournament(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True,
        verbose_name='название',
    )
    
    rules = models.TextField(
        verbose_name='правила',
    )
    
    goal = models.TextField(
        verbose_name='задача'
    )
    
    required_battles_count = models.PositiveIntegerField(
        verbose_name='необходимое количество боёв',
        help_text='сколько боёв необходимо сыграть чтобы результат был защитан',
        default=100,
    )
    
    tanks = models.ManyToManyField(
        'Tank',
        verbose_name='Танки',
    )
    
    total_prize = models.PositiveIntegerField(
        verbose_name='призовой фонд',
        default=0,
    )
    
    prize_first_place = models.PositiveIntegerField(
        verbose_name='приз за первое место',
    )
    
    prize_second_place = models.PositiveIntegerField(
        verbose_name='приз за второе место',
    )
    
    prize_third_place = models.PositiveIntegerField(
        verbose_name='приз за третье место',
    )
    
    start_time = models.DateTimeField(
        verbose_name='время начала'
    )
    
    end_time = models.DateTimeField(
        verbose_name='время окончания'
    )
    
    is_active = models.BooleanField(
        default=False,
        verbose_name='активен',
        # editable=False,
    )
    
    is_over = models.BooleanField(
        default=False,
        verbose_name='закончился',
        # editable=False,
    )
    
    created_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name='время создания',
        editable=False,
    )
    
    players = models.ManyToManyField(
        User,
        through='TournamentRecord',
    )
    
    preview = models.ImageField(
        verbose_name='превью',
        upload_to='tournaments/',
        default='tournaments/default_tournament_preview.png',
        help_text = 'размер фотографии должен быть 10x2\n в формате png',
        validators = [
            validate_image_file_extension,
            # ImageSizeValidator(10, 2),
        ],
    )
    
    class Meta:
        ordering = ['start_time']
        verbose_name = 'Турнир'
        verbose_name_plural = 'Турниры'
        default_related_name='tournaments'
        
        permissions = (
            ('can_enter', 'может учавствовать в турнирах'),
        )
        
    def __str__(self):
        return f'{self.name}'
    
    def get_absolute_url(self):
        return reverse("tournament:tournament_detail", kwargs={"pk": self.pk})
    
        

class TournamentRecord(models.Model):
    tournament = models.ForeignKey(
        'Tournament',
        on_delete=models.CASCADE,
        verbose_name='турнир',
        related_name='tournament_records'
    )
    
    player = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='игрок',
    )
    
    battle_count = models.PositiveIntegerField(
        verbose_name='количество боёв в турнире',
        default=0,
    )
    
    win_rate = models.FloatField(
        verbose_name='процент побед в турнире',
        default=0,
    )
    
    average_damage = models.FloatField(
        verbose_name='средний дамаг в турнире',
        default=0,
    )
    
    is_tracked = models.BooleanField(
        verbose_name='отслеживать прогресс',
        default=False,
    )
    
    account_battle_count = models.PositiveIntegerField(
        verbose_name='количество боёв на аккаунте',
        null=True,
        blank=True,
    )
    
    account_win_rate = models.FloatField(
        verbose_name='процент побед на аккаунте',
        null=True,
        blank=True,
    )
    
    account_average_damage = models.FloatField(
        verbose_name='средний дамаг на аккаунте',
        null=True,
        blank=True,
    )
    
    class Meta:
        verbose_name = 'Запись в турнирной таблице'
        verbose_name_plural = 'Записи в турнирной таблице'
        default_related_name = 'tournament_records'
        unique_together = ('tournament', 'player')
        
    def __str__(self):
        return f'{self.tournament} - {self.player} - {self.battle_count}'

tournament/forms.py
from django import forms

class ReplayForm(forms.Form):
    replay = forms.ImageField(
        widget=forms.widgets.ClearableFileInput(attrs={'multiple': True}),
        label='Выберите файл'
    )  

tournament/views.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView, View
from django.views.generic.edit import CreateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse, FileResponse
from .models import *
from .forms import *
from django.urls import reverse_lazy
from django.conf import settings
import os
from django.contrib.auth.decorators import login_required, permission_required
from .services.tournament import tournament_add_user, tournament_delete_user

class IndexView(TemplateView):
    template_name = 'tournament/index.html'


class ReplayFormView(FormView):
    template_name = 'tournament/upload_replay_form.html'
    form_class = ReplayForm
    success_url = reverse_lazy('tournament:index')
    
    def form_valid(self, form):
        uploaded_file = form.cleaned_data['replay']
        file_path = os.path.join(settings.REPLAYS_ROOT, uploaded_file.name)
        with open(file_path, 'wb') as file:
            for chunk in uploaded_file.chunks():
                file.write(chunk)
        return super().form_valid(form)

class ReplayListView(ListView):
    template_name = 'tournament/replay_list.html'
    context_object_name = 'replay_files_names'
    
    def get_replay_files_path(self):
        return [os.path.basename(file) for file in os.scandir(settings.REPLAYS_ROOT)]
        
    def get_queryset(self):
        return self.get_replay_files_path()
    
    
class ReplayDownload(View):
    def get(self, request, file_path):
        file_path = os.path.join(settings.REPLAYS_ROOT, file_path)
        return FileResponse(open(file_path, 'rb'), as_attachment=True)
    

class TournamentListView(ListView):
    model = Tournament
    paginate_by = 5
    
class TournamentDetailView(DetailView):
    model = Tournament
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user_in_current_tournament'] = self.request.user in self.object.players.all()
            if not context['user_in_current_tournament']:
                context['user_in_othe_tournament'] = bool(self.request.user.tournaments.all().count())
        return context
    

@login_required
@permission_required('tournament.can_enter', raise_exception=True)
def enter_tournament(request, pk):
    tournament_add_user(request.user, pk)
    return redirect('tournament:tournament_detail', pk=pk)

@login_required
def leave_tournament(request, pk):
    tournament_delete_user(request.user, pk)
    return redirect('tournament:tournament_detail', pk=pk)
    
    

    
    
# class CreateTankView(CreateView):
#     model = Tank
#     fields = '__all__'
#     success_url = reverse_lazy('accounts:register_done')

tournament/templates/tournament/index.html
<h1>Main page</h1>

tournament/templates/tournament/replay_list.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Загруженные реплеи</h1>
    <ul>
        {% for replay_name in replay_files_names %}
            <li>
                {{ replay_name }}<a href="{% url 'tournament:download_replay' replay_name %}"> | Download</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

tournament/templates/tournament/tournament_detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>{{ tournament }}</h1>
    <p>разная ифа...</p>
    {% if tournament.is_over %}
        <p>Турнир завершен</p>
    {% else %}
        {% if user_in_current_tournament %}
            <p>Вы учавствуете в турнире</p>
            {% if tournament.is_active %}
                <a href="{% url 'tournament:leave_tournament' pk=tournament.pk %}">Покинуть турнир</a>
                <p>Турнир уже идёт, если вы выйдете из него сейчас, то не сможете продлжыть принимать в нём участие</p>
            {% else %}
                <a href="{% url 'tournament:leave_tournament' pk=tournament.pk %}">Покинуть турнир</a>
                <p>Вы сможете попасть обратно в этот турнир, если выйдете сейчас</p>
            {% endif %}
        {% else %}
            {% if user_in_othe_tournament %}
                {% if tournament.is_active %}
                    <p>Вы не можете принять участие так как турнир уже идёт</p>
                {% else %}
                    <p>Вы не можете принять участие так как уже принимаете участи в турнире "{{ user.tournaments.first }}"</p>
                {% endif %}
            {% else %}
                {% if tournament.is_active %}
                    <p>Вы не можете принять участие так как турнир уже идёт</p>
                {% else %}
                    <a href="{% url 'tournament:enter_tournament' pk=tournament.pk %}">Вступить</a>
                {% endif %}
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock %}

tournament/templates/tournament/tournament_list.html
{% extends 'base/base.html' %}

{% block content %}
<h1>Турниры</h1>
<ul>
    {% for tournament in tournament_list %}
        <li>
            {% for tank in tournament.tanks.all %}
                <img src="{{ tank.image.url }}" alt="" width="50">
            {%  endfor %}
            <a href="{{ tournament.get_absolute_url }}">{{ tournament.name }}</a>
            <p>{{ tournament.goal }}</p>
            <h5>{{ tournament.total_prize }}</h5>
            <strong>{{ tournament.start_time }}</strong>
            <strong>{{ tournament.is_active }}</strong>
        </li>
        </li>
    {% endfor %}
</ul>
{% endblock %}

tournament/templates/tournament/upload_replay_form.html
{% extends 'base/base.html' %}
{%  load static %}

{% block content %}
    <h1>Загрузить реплей</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Загрузить реплей">
    </form>
{% endblock %} 



{% comment %} Тест фронтенда загрузки реплея {% endcomment %}
{% comment %} 
{% block content %}
    <h1>Загрузить реплей</h1>
    <form id="upload-container" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for error in form.replay.errors %}
            <p>{{ error }}</p>
        {% endfor %}
        <img id="upload-image" src="{% static 'img/upload_file_image.png' %}">
        <div>
            {{ form.replay }}
            {{ form.replay.label_tag }}
            <span>или перетащите его сюда</span>
        </div>
    </form>
{% endblock %} {% endcomment %}